name: matabari
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^2.0.1
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  carousel_slider: ^5.1.2
  get: ^4.7.3
  audioplayers: ^6.7.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  url_launcher: ^6.3.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Tripura Sundari-Photoroom 1.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/Tripura Sundari-Photoroom 1.png"
  macos:
    generate: true
    image_path: "assets/images/Tripura Sundari-Photoroom 1.png"
  web:
    generate: true
    image_path: "assets/images/Tripura Sundari-Photoroom 1.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
 
  fonts:
    - family: CormorantInfant
      fonts:
        - asset: assets/fonts/CormorantInfant-Regular.ttf
          weight: 600
        - asset: assets/fonts/CormorantInfant-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CormorantInfant-Bold.ttf
          weight: 700
    - family: AvenirNextCyr
      fonts:
        - asset: assets/fonts/Avenir Next Cyr Medium.ttf
          weight: 500
       
  
